'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace com.CustomerPoint.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LoadPageSoap", [Namespace]:="http://tempuri.org/CustomerPoint/LoadPage")>  _
    Public Class LoadPage
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accounts.infinibiz.com/customerpoint/LoadPage.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerPoint/LoadPage/InvokeCustomerPoint", RequestNamespace:="http://tempuri.org/CustomerPoint/LoadPage", ResponseNamespace:="http://tempuri.org/CustomerPoint/LoadPage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InvokeCustomerPoint(ByVal CustomerID As Integer, ByVal CustomerpointID As String) As String
            Dim results() As Object = Me.Invoke("InvokeCustomerPoint", New Object() {CustomerID, CustomerpointID})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginInvokeCustomerPoint(ByVal CustomerID As Integer, ByVal CustomerpointID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InvokeCustomerPoint", New Object() {CustomerID, CustomerpointID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndInvokeCustomerPoint(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
