'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace com.infinibiz.accounts
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MerchantServicesSoap", [Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class MerchantServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accounts.infinibiz.com/account/MerchantServices.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetTreeView_Merchant", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTreeView_Merchant(ByVal LoginInfo As LoginInfo_Merchant) As AccTreeViewResult
            Dim results() As Object = Me.Invoke("GetTreeView_Merchant", New Object() {LoginInfo})
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTreeView_Merchant(ByVal LoginInfo As LoginInfo_Merchant, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTreeView_Merchant", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTreeView_Merchant(ByVal asyncResult As System.IAsyncResult) As AccTreeViewResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetTreeView_Employee", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTreeView_Employee(ByVal LoginInfo As LoginInfo_Employee) As AccTreeViewResult
            Dim results() As Object = Me.Invoke("GetTreeView_Employee", New Object() {LoginInfo})
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTreeView_Employee(ByVal LoginInfo As LoginInfo_Employee, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTreeView_Employee", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTreeView_Employee(ByVal asyncResult As System.IAsyncResult) As AccTreeViewResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetTreeView", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTreeView() As AccTreeViewResult
            Dim results() As Object = Me.Invoke("GetTreeView", New Object(-1) {})
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTreeView(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTreeView", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTreeView(ByVal asyncResult As System.IAsyncResult) As AccTreeViewResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AccTreeViewResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/Encrypt_Merchant", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Encrypt_Merchant(ByVal LoginInfo As LoginInfo_Merchant) As EncryptResult
            Dim results() As Object = Me.Invoke("Encrypt_Merchant", New Object() {LoginInfo})
            Return CType(results(0),EncryptResult)
        End Function
        
        '<remarks/>
        Public Function BeginEncrypt_Merchant(ByVal LoginInfo As LoginInfo_Merchant, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Encrypt_Merchant", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEncrypt_Merchant(ByVal asyncResult As System.IAsyncResult) As EncryptResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EncryptResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/Encrypt_MerchantAndEmp"& _ 
"loyee", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Encrypt_MerchantAndEmployee(ByVal LoginInfo As UserInfo) As EncryptResult
            Dim results() As Object = Me.Invoke("Encrypt_MerchantAndEmployee", New Object() {LoginInfo})
            Return CType(results(0),EncryptResult)
        End Function
        
        '<remarks/>
        Public Function BeginEncrypt_MerchantAndEmployee(ByVal LoginInfo As UserInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Encrypt_MerchantAndEmployee", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEncrypt_MerchantAndEmployee(ByVal asyncResult As System.IAsyncResult) As EncryptResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EncryptResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetAllowedFolders", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllowedFolders(ByVal LoginInfo As UserInfo) As AllowedFoldersResult
            Dim results() As Object = Me.Invoke("GetAllowedFolders", New Object() {LoginInfo})
            Return CType(results(0),AllowedFoldersResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetAllowedFolders(ByVal LoginInfo As UserInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllowedFolders", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAllowedFolders(ByVal asyncResult As System.IAsyncResult) As AllowedFoldersResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AllowedFoldersResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetFolderLinks", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFolderLinks(ByVal info As UserAndFolderInfo) As FolderLinksResult
            Dim results() As Object = Me.Invoke("GetFolderLinks", New Object() {info})
            Return CType(results(0),FolderLinksResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetFolderLinks(ByVal info As UserAndFolderInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFolderLinks", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetFolderLinks(ByVal asyncResult As System.IAsyncResult) As FolderLinksResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),FolderLinksResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/MerchantServices/GetBizPlanServices", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBizPlanServices(ByVal LoginInfo As UserInfo) As String
            Dim results() As Object = Me.Invoke("GetBizPlanServices", New Object() {LoginInfo})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetBizPlanServices(ByVal LoginInfo As UserInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBizPlanServices", New Object() {LoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetBizPlanServices(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class LoginInfo_Merchant
        
        '<remarks/>
        Public CustomerID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class LinkInfo
        
        '<remarks/>
        Public [Text] As String
        
        '<remarks/>
        Public URL As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class FolderLinksResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Links() As LinkInfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class UserAndFolderInfo
        
        '<remarks/>
        Public LoginInfo As UserInfo
        
        '<remarks/>
        Public Finfo As FolderInfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class UserInfo
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        Public EmployeeID As String
        
        '<remarks/>
        Public IsMerchant As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class FolderInfo
        
        '<remarks/>
        Public ServiceID As String
        
        '<remarks/>
        Public ModelID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class AllowedFoldersResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public AllowedIDs() As FolderInfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class EncryptResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        Public AppendText As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class LoginInfo_Employee
        
        '<remarks/>
        Public CustomerID As String
        
        '<remarks/>
        Public EmployeeID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class AccTreeView
        
        '<remarks/>
        Public [Text] As String
        
        '<remarks/>
        Public URL As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public ChildNodes() As AccTreeView
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/MerchantServices")>  _
    Public Class AccTreeViewResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        Public AccTreeView As AccTreeView
    End Class
End Namespace
