'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace infinibiz_Services
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CustomerSoap", [Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class Customer
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accounts.infinibiz.com/account/customer.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/Customer/getCustomerInfo", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getCustomerInfo(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal info() As customerInfo) As customerInfoResult
            Dim results() As Object = Me.Invoke("getCustomerInfo", New Object() {info})
            Return CType(results(0),customerInfoResult)
        End Function
        
        '<remarks/>
        Public Function BegingetCustomerInfo(ByVal info() As customerInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCustomerInfo", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCustomerInfo(ByVal asyncResult As System.IAsyncResult) As customerInfoResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),customerInfoResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/Customer/getActivationInfo", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getActivationInfo(ByVal productinfo As activationinfo) As getActivationInfoResult
            Dim results() As Object = Me.Invoke("getActivationInfo", New Object() {productinfo})
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        Public Function BegingetActivationInfo(ByVal productinfo As activationinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getActivationInfo", New Object() {productinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetActivationInfo(ByVal asyncResult As System.IAsyncResult) As getActivationInfoResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/Customer/autoLogin", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function autoLogin(ByVal logininfo As AutoLoginStruct) As AutoLoginResult
            Dim results() As Object = Me.Invoke("autoLogin", New Object() {logininfo})
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        Public Function BeginautoLogin(ByVal logininfo As AutoLoginStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("autoLogin", New Object() {logininfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndautoLogin(ByVal asyncResult As System.IAsyncResult) As AutoLoginResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/Customer/logOff", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function logOff(ByVal logoffinfo As AutoLogOffStruct) As logoffReturnMsg
            Dim results() As Object = Me.Invoke("logOff", New Object() {logoffinfo})
            Return CType(results(0),logoffReturnMsg)
        End Function
        
        '<remarks/>
        Public Function BeginlogOff(ByVal logoffinfo As AutoLogOffStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("logOff", New Object() {logoffinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlogOff(ByVal asyncResult As System.IAsyncResult) As logoffReturnMsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),logoffReturnMsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accounts.infinibiz.Web/Customer/SingleSignin", RequestNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", ResponseNamespace:="http://tempuri.org/accounts.infinibiz.Web/Customer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SingleSignin(ByVal info As SingleSigninInfo) As SingleSigninResult
            Dim results() As Object = Me.Invoke("SingleSignin", New Object() {info})
            Return CType(results(0),SingleSigninResult)
        End Function
        
        '<remarks/>
        Public Function BeginSingleSignin(ByVal info As SingleSigninInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SingleSignin", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSingleSignin(ByVal asyncResult As System.IAsyncResult) As SingleSigninResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SingleSigninResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class customerInfo
        
        '<remarks/>
        Public customerID As String
        
        '<remarks/>
        Public refferID As String
        
        '<remarks/>
        Public productCode As String
        
        '<remarks/>
        Public quantity As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class SingleSigninResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public InternalCustomerID As String
        
        '<remarks/>
        Public InternalCustomerUID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class SingleSigninInfo
        
        '<remarks/>
        Public loginid As String
        
        '<remarks/>
        Public password As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class logoffReturnMsg
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class AutoLogOffStruct
        
        '<remarks/>
        Public sid As String
        
        '<remarks/>
        Public refId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class AutoLoginResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public newwin As String
        
        '<remarks/>
        Public winparam As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
        
        '<remarks/>
        Public link As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class AutoLoginStruct
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public loginid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class getActivationInfoResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public link As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class activationinfo
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public serialno As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public serviceid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/accounts.infinibiz.Web/Customer")>  _
    Public Class customerInfoResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public info() As customerInfo
    End Class
End Namespace
