'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
'
Namespace com.formationshouse.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FHservicesBinding", [Namespace]:="urn:FHservices"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(companyard)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(OfficerInfo))>  _
    Public Class FHservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.formationshouse.com/getinfo.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCustomerDomains", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getCustomerDomains(ByVal customer_uid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String()
            Dim results() As Object = Me.Invoke("getCustomerDomains", New Object() {customer_uid})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BegingetCustomerDomains(ByVal customer_uid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCustomerDomains", New Object() {customer_uid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCustomerDomains(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCompanyInfo", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getCompanyInfo(ByVal companyname As String, ByVal companynumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> CompanyInfo
            Dim results() As Object = Me.Invoke("getCompanyInfo", New Object() {companyname, companynumber})
            Return CType(results(0),CompanyInfo)
        End Function
        
        '<remarks/>
        Public Function BegingetCompanyInfo(ByVal companyname As String, ByVal companynumber As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCompanyInfo", New Object() {companyname, companynumber}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCompanyInfo(ByVal asyncResult As System.IAsyncResult) As CompanyInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CompanyInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCompanies", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getCompanies(ByVal customer_uid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> CompanyInfo()
            Dim results() As Object = Me.Invoke("getCompanies", New Object() {customer_uid})
            Return CType(results(0),CompanyInfo())
        End Function
        
        '<remarks/>
        Public Function BegingetCompanies(ByVal customer_uid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCompanies", New Object() {customer_uid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCompanies(ByVal asyncResult As System.IAsyncResult) As CompanyInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CompanyInfo())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCompanies", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function setLastArd(ByVal companyInfo As cinfo) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("setLastArd", New Object() {companyInfo})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginsetLastArd(ByVal companyInfo As cinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("setLastArd", New Object() {companyInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndsetLastArd(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCustomerInfo", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getCustomerInfo(ByVal customerid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> customerInfo
            Dim results() As Object = Me.Invoke("getCustomerInfo", New Object() {customerid})
            Return CType(results(0),customerInfo)
        End Function
        
        '<remarks/>
        Public Function BegingetCustomerInfo(ByVal customerid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCustomerInfo", New Object() {customerid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCustomerInfo(ByVal asyncResult As System.IAsyncResult) As customerInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),customerInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getArd", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getArd(ByVal companynames() As String) As <System.Xml.Serialization.SoapElementAttribute("return")> companyard()
            Dim results() As Object = Me.Invoke("getArd", New Object() {companynames})
            Return CType(results(0),companyard())
        End Function
        
        '<remarks/>
        Public Function BegingetArd(ByVal companynames() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getArd", New Object() {companynames}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetArd(ByVal asyncResult As System.IAsyncResult) As companyard()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),companyard())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#verifyCompany", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function verifyCompany(ByVal companynumber As String, ByVal companyname As String) As <System.Xml.Serialization.SoapElementAttribute("return")> compinfo
            Dim results() As Object = Me.Invoke("verifyCompany", New Object() {companynumber, companyname})
            Return CType(results(0),compinfo)
        End Function
        
        '<remarks/>
        Public Function BeginverifyCompany(ByVal companynumber As String, ByVal companyname As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("verifyCompany", New Object() {companynumber, companyname}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndverifyCompany(ByVal asyncResult As System.IAsyncResult) As compinfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),compinfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#getCompanyBySubid", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function getCompanyBySubid(ByVal customerid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> CompanyInfo
            Dim results() As Object = Me.Invoke("getCompanyBySubid", New Object() {customerid})
            Return CType(results(0),CompanyInfo)
        End Function
        
        '<remarks/>
        Public Function BegingetCompanyBySubid(ByVal customerid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getCompanyBySubid", New Object() {customerid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetCompanyBySubid(ByVal asyncResult As System.IAsyncResult) As CompanyInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CompanyInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("CompanyInfo", "urn:FHservices")>  _
    Public Class CompanyInfo
        
        '<remarks/>
        Public companyname As String
        
        '<remarks/>
        Public companynumber As String
        
        '<remarks/>
        Public eincdate As String
        
        '<remarks/>
        Public ard As String
        
        '<remarks/>
        Public ardlast As String
        
        '<remarks/>
        Public ardnext As String
        
        '<remarks/>
        Public ardcurrent As String
        
        '<remarks/>
        Public dissolvedate As String
        
        '<remarks/>
        Public taxcode As String
        
        '<remarks/>
        Public taxissuedate As String
        
        '<remarks/>
        Public returndate As String
        
        '<remarks/>
        Public nextreturndate As String
        
        '<remarks/>
        Public domainname As String
        
        '<remarks/>
        Public subaccount As String
        
        '<remarks/>
        Public dormant As String
        
        '<remarks/>
        Public telephone As String
        
        '<remarks/>
        Public fax As String
        
        '<remarks/>
        Public email As String
        
        '<remarks/>
        Public address As AddressInfo
        
        '<remarks/>
        Public officerinfo() As OfficerInfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("AddressInfo", "urn:FHservices")>  _
    Public Class AddressInfo
        
        '<remarks/>
        Public line1 As String
        
        '<remarks/>
        Public line2 As String
        
        '<remarks/>
        Public line3 As String
        
        '<remarks/>
        Public posttown As String
        
        '<remarks/>
        Public country As String
        
        '<remarks/>
        Public postcode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("compinfo", "urn:FHservices")>  _
    Public Class compinfo
        
        '<remarks/>
        Public ERRORCODE As Integer
        
        '<remarks/>
        Public companynumber As String
        
        '<remarks/>
        Public companyname As String
        
        '<remarks/>
        Public customerid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("companyard", "urn:FHservices")>  _
    Public Class companyard
        
        '<remarks/>
        Public companyname As String
        
        '<remarks/>
        Public ard As String
        
        '<remarks/>
        Public incdate As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("customerInfo", "urn:FHservices")>  _
    Public Class customerInfo
        
        '<remarks/>
        Public customer_id As String
        
        '<remarks/>
        Public ac As String
        
        '<remarks/>
        Public name As String
        
        '<remarks/>
        Public street As String
        
        '<remarks/>
        Public ccode As String
        
        '<remarks/>
        Public town As String
        
        '<remarks/>
        Public country As String
        
        '<remarks/>
        Public postcode As String
        
        '<remarks/>
        Public cont_name As String
        
        '<remarks/>
        Public telephone As String
        
        '<remarks/>
        Public fax As String
        
        '<remarks/>
        Public vat As String
        
        '<remarks/>
        Public fnew As String
        
        '<remarks/>
        Public fmodified As String
        
        '<remarks/>
        Public cart_customer_email As String
        
        '<remarks/>
        Public cart_customer_notes As String
        
        '<remarks/>
        Public cart_customer_uid As String
        
        '<remarks/>
        Public cart_customer_pass As String
        
        '<remarks/>
        Public cart_customer_state As String
        
        '<remarks/>
        Public store_name As String
        
        '<remarks/>
        Public vtime As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("cinfo", "urn:FHservices")>  _
    Public Class cinfo
        
        '<remarks/>
        Public companyname As String
        
        '<remarks/>
        Public companynumber As String
        
        '<remarks/>
        Public lastArd As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("OfficerInfo", "urn:FHservices")>  _
    Public Class OfficerInfo
        
        '<remarks/>
        Public corporate As Integer
        
        '<remarks/>
        Public type As Integer
        
        '<remarks/>
        Public surname As String
        
        '<remarks/>
        Public forename As String
        
        '<remarks/>
        Public appointmentdate As String
    End Class
End Namespace
