'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace BizAPI_EmailService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmailServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class EmailService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.reseller.com/common/EmailService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RREG", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RREG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal EmailAddress As String, ByVal CustomerAddress As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RREG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, EmailAddress, CustomerAddress})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RREG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal EmailAddress As String, ByVal CustomerAddress As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RREG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, EmailAddress, CustomerAddress}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RREG(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RDLA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RDLA(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RDLA", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RDLA(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RDLA", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RDLA(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RDNL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RDNL(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RDNL", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RDNL(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RDNL", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RDNL(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RLEX", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RLEX(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RLEX", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RLEX(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RLEX", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RLEX(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RCCP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RCCP(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RCCP", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RCCP(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RCCP", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RCCP(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RCLP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RCLP(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RCLP", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RCLP(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal OrderNo As String, ByVal OrderAmount As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RCLP", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, OrderNo, OrderAmount}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RCLP(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RCRG", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RCRG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ResellerURL As String, ByVal LoginID As String, ByVal Password As String, ByVal PhoneNo As String, ByVal CustomerAddress As String, ByVal ServicesInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RCRG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ResellerURL, LoginID, Password, PhoneNo, CustomerAddress, ServicesInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RCRG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ResellerURL As String, ByVal LoginID As String, ByVal Password As String, ByVal PhoneNo As String, ByVal CustomerAddress As String, ByVal ServicesInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RCRG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ResellerURL, LoginID, Password, PhoneNo, CustomerAddress, ServicesInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RCRG(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RCRR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RCRR(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal CustomerName As String, ByVal LoginID As String, ByVal Password As String, ByVal ServicesInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RCRR", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, CustomerName, LoginID, Password, ServicesInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RCRR(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal CustomerName As String, ByVal LoginID As String, ByVal Password As String, ByVal ServicesInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RCRR", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, CustomerName, LoginID, Password, ServicesInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RCRR(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RACT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RACT(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal MerchantWebURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Email As String, ByVal PhoneNo As String, ByVal Address As String, ByVal ServicesInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RACT", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, MerchantWebURL, LoginID, Password, Email, PhoneNo, Address, ServicesInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RACT(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal MerchantWebURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Email As String, ByVal PhoneNo As String, ByVal Address As String, ByVal ServicesInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RACT", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, MerchantWebURL, LoginID, Password, Email, PhoneNo, Address, ServicesInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RACT(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_ROAC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_ROAC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal MerchantWebURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Email As String, ByVal PhoneNo As String, ByVal Address As String, ByVal ServicesInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_ROAC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, MerchantWebURL, LoginID, Password, Email, PhoneNo, Address, ServicesInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_ROAC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerName As String, ByVal MerchantWebURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Email As String, ByVal PhoneNo As String, ByVal Address As String, ByVal ServicesInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_ROAC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, ResellerName, MerchantWebURL, LoginID, Password, Email, PhoneNo, Address, ServicesInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_ROAC(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RPAR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RPAR(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RPAR", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RPAR(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RPAR", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RPAR(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RPAC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RPAC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String, ByVal LiveID As String, ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RPAC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation, LiveID, Password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RPAC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String, ByVal LiveID As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RPAC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation, LiveID, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RPAC(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RPAN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RPAN(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RPAN", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RPAN(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RPAN", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RPAN(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RAPI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RAPI(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RAPI", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RAPI(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal ServiceInformation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RAPI", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, ServiceInformation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RAPI(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_RDRC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_RDRC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal DomainName As String, ByVal ServiceInformation As String, ByVal LiveID As String, ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_RDRC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, DomainName, ServiceInformation, LiveID, Password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_RDRC(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal CustomerName As String, ByVal DomainName As String, ByVal ServiceInformation As String, ByVal LiveID As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_RDRC", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, CustomerName, DomainName, ServiceInformation, LiveID, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_RDRC(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnableService_Error", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnableService_Error(ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerID As String, ByVal ResellerCustomerUID As String, ByVal OrderID As String, ByVal IsOrderSuccess As Boolean) As String
            Dim results() As Object = Me.Invoke("EnableService_Error", New Object() {To_EmailAddress, BCC_EmailAddress, LogPath, ResellerID, ResellerCustomerUID, OrderID, IsOrderSuccess})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginEnableService_Error(ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal ResellerID As String, ByVal ResellerCustomerUID As String, ByVal OrderID As String, ByVal IsOrderSuccess As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnableService_Error", New Object() {To_EmailAddress, BCC_EmailAddress, LogPath, ResellerID, ResellerCustomerUID, OrderID, IsOrderSuccess}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEnableService_Error(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_ICRG", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_ICRG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal LoginURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Name As String, ByVal Phone As String, ByVal Address As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_ICRG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, LoginURL, LoginID, Password, Name, Phone, Address})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_ICRG(ByVal MerchantID As String, ByVal To_EmailAddress As String, ByVal BCC_EmailAddress As String, ByVal LogPath As String, ByVal LoginURL As String, ByVal LoginID As String, ByVal Password As String, ByVal Name As String, ByVal Phone As String, ByVal Address As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_ICRG", New Object() {MerchantID, To_EmailAddress, BCC_EmailAddress, LogPath, LoginURL, LoginID, Password, Name, Phone, Address}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_ICRG(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_ISOD", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail_ISOD(ByVal MerchantID As String, ByVal XML As String) As String
            Dim results() As Object = Me.Invoke("SendEmail_ISOD", New Object() {MerchantID, XML})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSendEmail_ISOD(ByVal MerchantID As String, ByVal XML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendEmail_ISOD", New Object() {MerchantID, XML}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendEmail_ISOD(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
