'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace AccServices
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FHservicesBinding", [Namespace]:="urn:FHservices")>  _
    Public Class FHservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.formationshouse.com/accservices.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#submitDCA", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function submitDCA(ByVal forminfo As dcaInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> ReturnMsg
            Dim results() As Object = Me.Invoke("submitDCA", New Object() {forminfo})
            Return CType(results(0),ReturnMsg)
        End Function
        
        '<remarks/>
        Public Function BeginsubmitDCA(ByVal forminfo As dcaInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("submitDCA", New Object() {forminfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndsubmitDCA(ByVal asyncResult As System.IAsyncResult) As ReturnMsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ReturnMsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:FHservices#submitDCA", RequestNamespace:="urn:FHservices", ResponseNamespace:="urn:FHservices")>  _
        Public Function updateAccountSubid(ByVal updateinfo As subaccountInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> updateMsg
            Dim results() As Object = Me.Invoke("updateAccountSubid", New Object() {updateinfo})
            Return CType(results(0),updateMsg)
        End Function
        
        '<remarks/>
        Public Function BeginupdateAccountSubid(ByVal updateinfo As subaccountInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("updateAccountSubid", New Object() {updateinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndupdateAccountSubid(ByVal asyncResult As System.IAsyncResult) As updateMsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),updateMsg)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("dcaInfo", "urn:FHservices")>  _
    Public Class dcaInfo
        
        '<remarks/>
        Public companynumber As String
        
        '<remarks/>
        Public accDate As String
        
        '<remarks/>
        Public currentyear As annualInfo
        
        '<remarks/>
        Public previousyear As annualInfo
        
        '<remarks/>
        Public isfirstyear As Decimal
        
        '<remarks/>
        Public allothedSharesNum As Decimal
        
        '<remarks/>
        Public totalSharesVal As Decimal
        
        '<remarks/>
        Public considerationVal As Decimal
        
        '<remarks/>
        Public isAgent As Decimal
        
        '<remarks/>
        Public isStatuary As Decimal
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("annualInfo", "urn:FHservices")>  _
    Public Class annualInfo
        
        '<remarks/>
        Public year As Decimal
        
        '<remarks/>
        Public unpaidsharecapital As Decimal
        
        '<remarks/>
        Public cash As Decimal
        
        '<remarks/>
        Public netassets As Decimal
        
        '<remarks/>
        Public shfunds As Decimal
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("updateMsg", "urn:FHservices")>  _
    Public Class updateMsg
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("subaccountInfo", "urn:FHservices")>  _
    Public Class subaccountInfo
        
        '<remarks/>
        Public companyname As String
        
        '<remarks/>
        Public companynumber As String
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public subaccount As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ReturnMsg", "urn:FHservices")>  _
    Public Class ReturnMsg
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public REFERENCEID As Decimal
    End Class
End Namespace
