'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace www.Athene.com
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AtheneSoap", [Namespace]:="http://tempuri.org/AtheneSystem/Athene")>  _
    Public Class Athene
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accounts.infinibiz.com/AtheneSystem/AtheneService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtheneSystem/Athene/AthenaInsertQuestionAnswer", RequestNamespace:="http://tempuri.org/AtheneSystem/Athene", ResponseNamespace:="http://tempuri.org/AtheneSystem/Athene", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AthenaInsertQuestionAnswer(ByVal QuestionId As Integer, ByVal Question As String, ByVal Answer As String, ByVal CategoryId As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer) As ResultMessage
            Dim results() As Object = Me.Invoke("AthenaInsertQuestionAnswer", New Object() {QuestionId, Question, Answer, CategoryId, Customerid, EmployeeId})
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        Public Function BeginAthenaInsertQuestionAnswer(ByVal QuestionId As Integer, ByVal Question As String, ByVal Answer As String, ByVal CategoryId As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AthenaInsertQuestionAnswer", New Object() {QuestionId, Question, Answer, CategoryId, Customerid, EmployeeId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAthenaInsertQuestionAnswer(ByVal asyncResult As System.IAsyncResult) As ResultMessage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtheneSystem/Athene/AthenaUpdateQuestionAnswer", RequestNamespace:="http://tempuri.org/AtheneSystem/Athene", ResponseNamespace:="http://tempuri.org/AtheneSystem/Athene", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AthenaUpdateQuestionAnswer(ByVal QuestionId As Integer, ByVal Question As String, ByVal Answer As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer) As ResultMessage
            Dim results() As Object = Me.Invoke("AthenaUpdateQuestionAnswer", New Object() {QuestionId, Question, Answer, Customerid, EmployeeId})
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        Public Function BeginAthenaUpdateQuestionAnswer(ByVal QuestionId As Integer, ByVal Question As String, ByVal Answer As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AthenaUpdateQuestionAnswer", New Object() {QuestionId, Question, Answer, Customerid, EmployeeId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAthenaUpdateQuestionAnswer(ByVal asyncResult As System.IAsyncResult) As ResultMessage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtheneSystem/Athene/AthenaInsertCategory", RequestNamespace:="http://tempuri.org/AtheneSystem/Athene", ResponseNamespace:="http://tempuri.org/AtheneSystem/Athene", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AthenaInsertCategory(ByVal CategoryId As Integer, ByVal CategoryName As String, ByVal ParentId As Integer, ByVal Customerid As Integer, ByVal EmployeeId As Integer) As ResultMessage
            Dim results() As Object = Me.Invoke("AthenaInsertCategory", New Object() {CategoryId, CategoryName, ParentId, Customerid, EmployeeId})
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        Public Function BeginAthenaInsertCategory(ByVal CategoryId As Integer, ByVal CategoryName As String, ByVal ParentId As Integer, ByVal Customerid As Integer, ByVal EmployeeId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AthenaInsertCategory", New Object() {CategoryId, CategoryName, ParentId, Customerid, EmployeeId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAthenaInsertCategory(ByVal asyncResult As System.IAsyncResult) As ResultMessage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtheneSystem/Athene/AthenaUpdateCategory", RequestNamespace:="http://tempuri.org/AtheneSystem/Athene", ResponseNamespace:="http://tempuri.org/AtheneSystem/Athene", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AthenaUpdateCategory(ByVal CategoryId As String, ByVal CategoryName As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer) As ResultMessage
            Dim results() As Object = Me.Invoke("AthenaUpdateCategory", New Object() {CategoryId, CategoryName, Customerid, EmployeeId})
            Return CType(results(0),ResultMessage)
        End Function
        
        '<remarks/>
        Public Function BeginAthenaUpdateCategory(ByVal CategoryId As String, ByVal CategoryName As String, ByVal Customerid As Integer, ByVal EmployeeId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AthenaUpdateCategory", New Object() {CategoryId, CategoryName, Customerid, EmployeeId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAthenaUpdateCategory(ByVal asyncResult As System.IAsyncResult) As ResultMessage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultMessage)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/AtheneSystem/Athene")>  _
    Public Class ResultMessage
        
        '<remarks/>
        Public Message As String
    End Class
End Namespace
