'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace com.webtracker.webservices
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebTrackerServicesBinding", [Namespace]:="urn:WebTrackerServices")>  _
    Public Class WebTrackerServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.webtracker.com/tracker.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WebTrackerServices#startSession", RequestNamespace:="urn:WebTrackerServices", ResponseNamespace:="urn:WebTrackerServices")>  _
        Public Function startSession(ByVal sessionInfo As sessionInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> trackInfo
            Dim results() As Object = Me.Invoke("startSession", New Object() {sessionInfo})
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        Public Function BeginstartSession(ByVal sessionInfo As sessionInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("startSession", New Object() {sessionInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndstartSession(ByVal asyncResult As System.IAsyncResult) As trackInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WebTrackerServices#updateSession", RequestNamespace:="urn:WebTrackerServices", ResponseNamespace:="urn:WebTrackerServices")>  _
        Public Function updateSession(ByVal sessionId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> trackInfo
            Dim results() As Object = Me.Invoke("updateSession", New Object() {sessionId})
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        Public Function BeginupdateSession(ByVal sessionId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("updateSession", New Object() {sessionId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndupdateSession(ByVal asyncResult As System.IAsyncResult) As trackInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WebTrackerServices#getTrackDetails", RequestNamespace:="urn:WebTrackerServices", ResponseNamespace:="urn:WebTrackerServices")>  _
        Public Function getTrackDetails(ByVal detailInfo As detailInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> trackInfo
            Dim results() As Object = Me.Invoke("getTrackDetails", New Object() {detailInfo})
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        Public Function BegingetTrackDetails(ByVal detailInfo As detailInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getTrackDetails", New Object() {detailInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetTrackDetails(ByVal asyncResult As System.IAsyncResult) As trackInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WebTrackerServices#getTrackHistory", RequestNamespace:="urn:WebTrackerServices", ResponseNamespace:="urn:WebTrackerServices")>  _
        Public Function getTrackHistory(ByVal detailInfo As detailInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> trackInfo
            Dim results() As Object = Me.Invoke("getTrackHistory", New Object() {detailInfo})
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        Public Function BegingetTrackHistory(ByVal detailInfo As detailInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getTrackHistory", New Object() {detailInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetTrackHistory(ByVal asyncResult As System.IAsyncResult) As trackInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WebTrackerServices#addProject", RequestNamespace:="urn:WebTrackerServices", ResponseNamespace:="urn:WebTrackerServices")>  _
        Public Function addProject(ByVal projectInfo As String) As <System.Xml.Serialization.SoapElementAttribute("return")> trackInfo
            Dim results() As Object = Me.Invoke("addProject", New Object() {projectInfo})
            Return CType(results(0),trackInfo)
        End Function
        
        '<remarks/>
        Public Function BeginaddProject(ByVal projectInfo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("addProject", New Object() {projectInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndaddProject(ByVal asyncResult As System.IAsyncResult) As trackInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),trackInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("sessionInfo", "urn:WebTrackerServices")>  _
    Public Class sessionInfo
        
        '<remarks/>
        Public siteUrl As String
        
        '<remarks/>
        Public siteName As String
        
        '<remarks/>
        Public siteCode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("detailInfo", "urn:WebTrackerServices")>  _
    Public Class detailInfo
        
        '<remarks/>
        Public sessionId As String
        
        '<remarks/>
        Public trackId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("trackInfo", "urn:WebTrackerServices")>  _
    Public Class trackInfo
        
        '<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")>  _
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public data As String
    End Class
End Namespace
