'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace com.infinibiz.accounts
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LoginSoap", [Namespace]:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login")>  _
    Public Class Login
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://accounts.infinibiz.com/account/login.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login/AutoLogin", RequestNamespace:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login", ResponseNamespace:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AutoLogin(ByVal logininfo As AutoLoginStruct) As AutoLoginResult
            Dim results() As Object = Me.Invoke("AutoLogin", New Object() {logininfo})
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        Public Function BeginAutoLogin(ByVal logininfo As AutoLoginStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AutoLogin", New Object() {logininfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAutoLogin(ByVal asyncResult As System.IAsyncResult) As AutoLoginResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login/LogOff", RequestNamespace:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login", ResponseNamespace:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LogOff(ByVal logoffinfo As AutoLogOffStruct) As logoffReturnMsg
            Dim results() As Object = Me.Invoke("LogOff", New Object() {logoffinfo})
            Return CType(results(0),logoffReturnMsg)
        End Function
        
        '<remarks/>
        Public Function BeginLogOff(ByVal logoffinfo As AutoLogOffStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LogOff", New Object() {logoffinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLogOff(ByVal asyncResult As System.IAsyncResult) As logoffReturnMsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),logoffReturnMsg)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login")>  _
    Public Class AutoLoginStruct
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public loginid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login")>  _
    Public Class logoffReturnMsg
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login")>  _
    Public Class AutoLogOffStruct
        
        '<remarks/>
        Public sid As String
        
        '<remarks/>
        Public refId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://accounts.infinibiz.com/InfiniLogic.AccountsCentre.Web/Login")>  _
    Public Class AutoLoginResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public newwin As String
        
        '<remarks/>
        Public winparam As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
        
        '<remarks/>
        Public link As String
    End Class
End Namespace
