'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2379
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2379.
'
Namespace FHResellerCustomer
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IBZservicesBinding", [Namespace]:="urn:IBZservices"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(pnameinfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(packageprodinfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(pcodeinfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(infolist)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(productsinfo))>  _
    Public Class IBZservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.infinibiz.com/customer.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#PayOrder", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function payOrder(ByVal orderinfo As orderinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("payOrder", New Object() {orderinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginpayOrder(ByVal orderinfo As orderinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("payOrder", New Object() {orderinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndpayOrder(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#AddNewOrder", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function addNewOrder(ByVal orderdetails As orderdetails) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("addNewOrder", New Object() {orderdetails})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginaddNewOrder(ByVal orderdetails As orderdetails, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("addNewOrder", New Object() {orderdetails}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndaddNewOrder(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getInactiveProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getInactiveProducts(ByVal getInactiveProductsRequest As getInactiveProductsRequest) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> getInactiveProductsResponse
            Dim results() As Object = Me.Invoke("getInactiveProducts", New Object() {getInactiveProductsRequest})
            Return CType(results(0),getInactiveProductsResponse)
        End Function
        
        '<remarks/>
        Public Function BegingetInactiveProducts(ByVal getInactiveProductsRequest As getInactiveProductsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getInactiveProducts", New Object() {getInactiveProductsRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetInactiveProducts(ByVal asyncResult As System.IAsyncResult) As getInactiveProductsResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),getInactiveProductsResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#ActivateProduct", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function activateProducts(ByVal activationinfo As activationinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("activateProducts", New Object() {activationinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginactivateProducts(ByVal activationinfo As activationinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("activateProducts", New Object() {activationinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactivateProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#activateGlobalProducts", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function activateGlobalProducts(ByVal activationinfo As activationinfo) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> returnmsg
            Dim results() As Object = Me.Invoke("activateGlobalProducts", New Object() {activationinfo})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginactivateGlobalProducts(ByVal activationinfo As activationinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("activateGlobalProducts", New Object() {activationinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndactivateGlobalProducts(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#autoLogin", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function autoLogin(ByVal autoLoginParam As autoLoginParam) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> autoLoginReturnmsg
            Dim results() As Object = Me.Invoke("autoLogin", New Object() {autoLoginParam})
            Return CType(results(0),autoLoginReturnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginautoLogin(ByVal autoLoginParam As autoLoginParam, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("autoLogin", New Object() {autoLoginParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndautoLogin(ByVal asyncResult As System.IAsyncResult) As autoLoginReturnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),autoLoginReturnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#preActivate", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function preActivate(ByVal preorderinfo As preActivateParam) As <System.Xml.Serialization.SoapElementAttribute("returnmsg")> autoLoginReturnmsg
            Dim results() As Object = Me.Invoke("preActivate", New Object() {preorderinfo})
            Return CType(results(0),autoLoginReturnmsg)
        End Function
        
        '<remarks/>
        Public Function BeginpreActivate(ByVal preorderinfo As preActivateParam, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("preActivate", New Object() {preorderinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndpreActivate(ByVal asyncResult As System.IAsyncResult) As autoLoginReturnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),autoLoginReturnmsg)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("orderinfo", "urn:IBZservices")>  _
    Public Class orderinfo
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public trackingid As String
        
        '<remarks/>
        Public invoiceno As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("pnameinfo", "urn:IBZservices")>  _
    Public Class pnameinfo
        
        '<remarks/>
        Public pcode As String
        
        '<remarks/>
        Public cname As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("preActivateParam", "urn:IBZservices")>  _
    Public Class preActivateParam
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public productname() As pnameinfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("autoLoginReturnmsg", "urn:IBZservices")>  _
    Public Class autoLoginReturnmsg
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
        
        '<remarks/>
        Public link As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("autoLoginParam", "urn:IBZservices")>  _
    Public Class autoLoginParam
        
        '<remarks/>
        Public parentid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
        
        '<remarks/>
        Public targeturl As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public language As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("packageprodinfo", "urn:IBZservices")>  _
    Public Class packageprodinfo
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public serialno As Integer
        
        '<remarks/>
        Public newserialno As Integer
        
        '<remarks/>
        Public renewable As Integer
        
        '<remarks/>
        Public renewduration As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("pcodeinfo", "urn:IBZservices")>  _
    Public Class pcodeinfo
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public serialno As Integer
        
        '<remarks/>
        Public newserialno As Integer
        
        '<remarks/>
        Public renewable As Integer
        
        '<remarks/>
        Public renewduration As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("activationinfo", "urn:IBZservices")>  _
    Public Class activationinfo
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public entityid As String
        
        '<remarks/>
        Public entityname As String
        
        '<remarks/>
        Public referrer As String
        
        '<remarks/>
        Public globalcompanyid As String
        
        '<remarks/>
        Public productcodes() As pcodeinfo
        
        '<remarks/>
        Public packageinfo() As packageprodinfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("infolist", "urn:IBZservices")>  _
    Public Class infolist
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public serialno As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("getInactiveProductsResponse", "urn:IBZservices")>  _
    Public Class getInactiveProductsResponse
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public info() As infolist
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("getInactiveProductsRequest", "urn:IBZservices")>  _
    Public Class getInactiveProductsRequest
        
        '<remarks/>
        Public customeruid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("productsinfo", "urn:IBZservices")>  _
    Public Class productsinfo
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public quantity As Decimal
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("orderdetails", "urn:IBZservices")>  _
    Public Class orderdetails
        
        '<remarks/>
        Public reselleruid As String
        
        '<remarks/>
        Public customeruid As String
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public trackingid As String
        
        '<remarks/>
        Public paid As String
        
        '<remarks/>
        Public invoiceno As String
        
        '<remarks/>
        Public totalamount As String
        
        '<remarks/>
        Public products() As productsinfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("returnmsg", "urn:IBZservices")>  _
    Public Class returnmsg
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
End Namespace
