'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
'
Namespace com.infinibiz.reseller
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ResellerServicesSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class ResellerServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://reseller.infinibiz.com/WebService/ResellerServices.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/autoLoginWithLiveID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function autoLoginWithLiveID(ByVal info As LiveLoginInfo) As AutoLoginResult
            Dim results() As Object = Me.Invoke("autoLoginWithLiveID", New Object() {info})
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        Public Function BeginautoLoginWithLiveID(ByVal info As LiveLoginInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("autoLoginWithLiveID", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndautoLoginWithLiveID(ByVal asyncResult As System.IAsyncResult) As AutoLoginResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/autoLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function autoLogin(ByVal logininfo As LoginInfo) As AutoLoginResult
            Dim results() As Object = Me.Invoke("autoLogin", New Object() {logininfo})
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        Public Function BeginautoLogin(ByVal logininfo As LoginInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("autoLogin", New Object() {logininfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndautoLogin(ByVal asyncResult As System.IAsyncResult) As AutoLoginResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getActivationInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getActivationInfo(ByVal productinfo As activationinfo) As getActivationInfoResult
            Dim results() As Object = Me.Invoke("getActivationInfo", New Object() {productinfo})
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        Public Function BegingetActivationInfo(ByVal productinfo As activationinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getActivationInfo", New Object() {productinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetActivationInfo(ByVal asyncResult As System.IAsyncResult) As getActivationInfoResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTreeView", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTreeView(ByVal MyInfo As CallerInfo, ByVal Parent As ParentNode) As GetTreeViewResult
            Dim results() As Object = Me.Invoke("GetTreeView", New Object() {MyInfo, Parent})
            Return CType(results(0),GetTreeViewResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTreeView(ByVal MyInfo As CallerInfo, ByVal Parent As ParentNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTreeView", New Object() {MyInfo, Parent}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTreeView(ByVal asyncResult As System.IAsyncResult) As GetTreeViewResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetTreeViewResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTreeViewByXML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTreeViewByXML(ByVal MyInfo As CallerInfo, ByVal StrXML As String) As GetTreeViewResult
            Dim results() As Object = Me.Invoke("GetTreeViewByXML", New Object() {MyInfo, StrXML})
            Return CType(results(0),GetTreeViewResult)
        End Function
        
        '<remarks/>
        Public Function BeginGetTreeViewByXML(ByVal MyInfo As CallerInfo, ByVal StrXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTreeViewByXML", New Object() {MyInfo, StrXML}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTreeViewByXML(ByVal asyncResult As System.IAsyncResult) As GetTreeViewResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetTreeViewResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class LiveLoginInfo
        
        '<remarks/>
        Public liveid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class CallerInfo
        
        '<remarks/>
        Public customeruid As Long
        
        '<remarks/>
        Public sessionid As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public referrer As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class GetTreeViewResult
        
        '<remarks/>
        Public ErrorCode As Short
        
        '<remarks/>
        Public ErrorDesc As String
        
        '<remarks/>
        Public ResultHTML As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class activationinfo
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public serialno As String
        
        '<remarks/>
        Public serviceid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class LoginInfo
        
        '<remarks/>
        Public customeruid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class ParentNode
        
        '<remarks/>
        Public [text] As String
        
        '<remarks/>
        Public link As String
        
        '<remarks/>
        Public imagepath As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public childnodes() As ParentNode
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class getActivationInfoResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public link As String
        
        '<remarks/>
        Public value As String
        
        '<remarks/>
        Public variablename As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class AutoLoginResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public link As Object
    End Class
End Namespace
