'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
'
Namespace com.reseller.webservices
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ResellerServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class ResellerService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.reseller.com/resellerbuilder/Services/ResellerService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buildreseller", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function buildreseller(ByVal rinfo As resellerinfo) As buildresellerresult
            Dim results() As Object = Me.Invoke("buildreseller", New Object() {rinfo})
            Return CType(results(0),buildresellerresult)
        End Function
        
        '<remarks/>
        Public Function Beginbuildreseller(ByVal rinfo As resellerinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("buildreseller", New Object() {rinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endbuildreseller(ByVal asyncResult As System.IAsyncResult) As buildresellerresult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),buildresellerresult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrybuildreseller", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function retrybuildreseller(ByVal rinfo As resellerinfo, ByVal continuefromstep As ContinuityStep) As buildresellerresult
            Dim results() As Object = Me.Invoke("retrybuildreseller", New Object() {rinfo, continuefromstep})
            Return CType(results(0),buildresellerresult)
        End Function
        
        '<remarks/>
        Public Function Beginretrybuildreseller(ByVal rinfo As resellerinfo, ByVal continuefromstep As ContinuityStep, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("retrybuildreseller", New Object() {rinfo, continuefromstep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endretrybuildreseller(ByVal asyncResult As System.IAsyncResult) As buildresellerresult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),buildresellerresult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/acknowledgereseller", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function acknowledgereseller(ByVal serviceresponse As acknowledgedata) As acknowledgeresult
            Dim results() As Object = Me.Invoke("acknowledgereseller", New Object() {serviceresponse})
            Return CType(results(0),acknowledgeresult)
        End Function
        
        '<remarks/>
        Public Function Beginacknowledgereseller(ByVal serviceresponse As acknowledgedata, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("acknowledgereseller", New Object() {serviceresponse}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endacknowledgereseller(ByVal asyncResult As System.IAsyncResult) As acknowledgeresult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),acknowledgeresult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateWebsiteForMerchant", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateWebsiteForMerchant(ByVal rinfo As resellerinfo) As buildresellerresult
            Dim results() As Object = Me.Invoke("CreateWebsiteForMerchant", New Object() {rinfo})
            Return CType(results(0),buildresellerresult)
        End Function
        
        '<remarks/>
        Public Function BeginCreateWebsiteForMerchant(ByVal rinfo As resellerinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateWebsiteForMerchant", New Object() {rinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCreateWebsiteForMerchant(ByVal asyncResult As System.IAsyncResult) As buildresellerresult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),buildresellerresult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class resellerinfo
        
        '<remarks/>
        Public resellerid As String
        
        '<remarks/>
        Public generatorid As String
        
        '<remarks/>
        Public resellerurl As String
        
        '<remarks/>
        Public currencydbid As String
        
        '<remarks/>
        Public orderid As String
        
        '<remarks/>
        Public sendemail As Boolean
        
        '<remarks/>
        Public isinfinishopcustomer As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class acknowledgeresult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class acknowledgedata
        
        '<remarks/>
        Public RESELLERID As String
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public RETURNLOG As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class buildresellerresult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum ContinuityStep
        
        '<remarks/>
        None
        
        '<remarks/>
        AddResellerInFormationsHouse
        
        '<remarks/>
        AddResellerInInfiniShop
        
        '<remarks/>
        AddResellerIP
        
        '<remarks/>
        AddResellerProducts
        
        '<remarks/>
        AddResellerAsMerchant
        
        '<remarks/>
        CallIShopAdminWebService
    End Enum
End Namespace
