'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
'
Namespace com.reseller.webservices1
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceActivationSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class ServiceActivation
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.reseller.com/reseller/ServiceActivation.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnabledServices", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnabledServices(ByVal ResellerID As Integer, ByVal OrderID As Integer, ByVal IsOrderSuccess As Boolean, ByVal PayMode As String) As Object
            Dim results() As Object = Me.Invoke("EnabledServices", New Object() {ResellerID, OrderID, IsOrderSuccess, PayMode})
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        Public Function BeginEnabledServices(ByVal ResellerID As Integer, ByVal OrderID As Integer, ByVal IsOrderSuccess As Boolean, ByVal PayMode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnabledServices", New Object() {ResellerID, OrderID, IsOrderSuccess, PayMode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEnabledServices(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrderActivationTrack", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddOrderActivationTrack(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal Info() As ActivationTrackInfo) As AddOrderActivationTrackResult
            Dim results() As Object = Me.Invoke("AddOrderActivationTrack", New Object() {Info})
            Return CType(results(0),AddOrderActivationTrackResult)
        End Function
        
        '<remarks/>
        Public Function BeginAddOrderActivationTrack(ByVal Info() As ActivationTrackInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddOrderActivationTrack", New Object() {Info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddOrderActivationTrack(ByVal asyncResult As System.IAsyncResult) As AddOrderActivationTrackResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AddOrderActivationTrackResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsOrderActivated", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsOrderActivated(ByVal Info As IsOrderActivatedInfo) As IsOrderActivatedResult
            Dim results() As Object = Me.Invoke("IsOrderActivated", New Object() {Info})
            Return CType(results(0),IsOrderActivatedResult)
        End Function
        
        '<remarks/>
        Public Function BeginIsOrderActivated(ByVal Info As IsOrderActivatedInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsOrderActivated", New Object() {Info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndIsOrderActivated(ByVal asyncResult As System.IAsyncResult) As IsOrderActivatedResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),IsOrderActivatedResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class AddOrderActivationTrackResult
        
        '<remarks/>
        Public ERRORCODE As Integer
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class ActivationTrackInfo
        
        '<remarks/>
        Public ResellerID As String
        
        '<remarks/>
        Public OrderID As String
        
        '<remarks/>
        Public CompanyID As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Detail() As ActivationTrackDetail
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class ActivationTrackDetail
        
        '<remarks/>
        Public ProductCode As String
        
        '<remarks/>
        Public FHSerialNo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class IsOrderActivatedInfo
        
        '<remarks/>
        Public ResellerID As String
        
        '<remarks/>
        Public OrderID As String
        
        '<remarks/>
        Public ProductCode As String
        
        '<remarks/>
        Public FHSerialNo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class IsOrderActivatedResult
        
        '<remarks/>
        Public ERRORCODE As Integer
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public OrderAlreadyActivated As Boolean
        
        '<remarks/>
        Public CompanyID As Long
    End Class
End Namespace
