'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace com.infinioffice.crm.services
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CRMservicesBinding", [Namespace]:="urn:CRMservices"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(sinfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ExtraServices))>  _
    Public Class CRMservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://services.crm.infinioffice.com/common.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddMerchant", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddMerchant(ByVal merchantData As MerchantData, ByVal companyName As String, ByVal childId As String, ByVal childUid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddMerchant", New Object() {merchantData, companyName, childId, childUid})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddMerchant(ByVal merchantData As MerchantData, ByVal companyName As String, ByVal childId As String, ByVal childUid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddMerchant", New Object() {merchantData, companyName, childId, childUid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddMerchant(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddCustomer", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddCustomer(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddCustomer", New Object() {merchantData, customerData, childId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddCustomer(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddCustomer", New Object() {merchantData, customerData, childId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddCustomer(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddEmployee", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddEmployee(ByVal merchantId As String, ByVal merchantUid As String, ByVal merchantPassword As String, ByVal customerId As String, ByVal customerUid As String, ByVal childId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddEmployee", New Object() {merchantId, merchantUid, merchantPassword, customerId, customerUid, childId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddEmployee(ByVal merchantId As String, ByVal merchantUid As String, ByVal merchantPassword As String, ByVal customerId As String, ByVal customerUid As String, ByVal childId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddEmployee", New Object() {merchantId, merchantUid, merchantPassword, customerId, customerUid, childId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddEmployee(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddSupplier", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddSupplier(ByVal merchantId As String, ByVal merchantUid As String, ByVal merchantPassword As String, ByVal customerId As String, ByVal customerUid As String, ByVal childId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddSupplier", New Object() {merchantId, merchantUid, merchantPassword, customerId, customerUid, childId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddSupplier(ByVal merchantId As String, ByVal merchantUid As String, ByVal merchantPassword As String, ByVal customerId As String, ByVal customerUid As String, ByVal childId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddSupplier", New Object() {merchantId, merchantUid, merchantPassword, customerId, customerUid, childId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddSupplier(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddHRProcess", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddHRProcess(ByVal merchantId As String, ByVal merchantUid As String, ByVal childId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddHRProcess", New Object() {merchantId, merchantUid, childId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddHRProcess(ByVal merchantId As String, ByVal merchantUid As String, ByVal childId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddHRProcess", New Object() {merchantId, merchantUid, childId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddHRProcess(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddProcesses", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddProcesses(ByVal servicesInfo As ServicesInfo) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddProcesses", New Object() {servicesInfo})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddProcesses(ByVal servicesInfo As ServicesInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddProcesses", New Object() {servicesInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddProcesses(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#LoginMerchant", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function LoginMerchant(ByVal merchantId As String, ByVal merchantUid As String, ByVal password As String, ByVal childId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> LoginResponse
            Dim results() As Object = Me.Invoke("LoginMerchant", New Object() {merchantId, merchantUid, password, childId})
            Return CType(results(0),LoginResponse)
        End Function
        
        '<remarks/>
        Public Function BeginLoginMerchant(ByVal merchantId As String, ByVal merchantUid As String, ByVal password As String, ByVal childId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoginMerchant", New Object() {merchantId, merchantUid, password, childId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLoginMerchant(ByVal asyncResult As System.IAsyncResult) As LoginResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),LoginResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#LoginCustomer", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function LoginCustomer(ByVal customerUid As String, ByVal password As String, ByVal merchantId As String, ByVal merchantPassword As String, ByVal childId As String, ByVal services As ServiceData) As <System.Xml.Serialization.SoapElementAttribute("return")> LoginResponse
            Dim results() As Object = Me.Invoke("LoginCustomer", New Object() {customerUid, password, merchantId, merchantPassword, childId, services})
            Return CType(results(0),LoginResponse)
        End Function
        
        '<remarks/>
        Public Function BeginLoginCustomer(ByVal customerUid As String, ByVal password As String, ByVal merchantId As String, ByVal merchantPassword As String, ByVal childId As String, ByVal services As ServiceData, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoginCustomer", New Object() {customerUid, password, merchantId, merchantPassword, childId, services}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLoginCustomer(ByVal asyncResult As System.IAsyncResult) As LoginResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),LoginResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#LoginCustomer", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function VerifyProject(ByVal projectId As String, ByVal sessionId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> VerifyProjectResponse
            Dim results() As Object = Me.Invoke("VerifyProject", New Object() {projectId, sessionId})
            Return CType(results(0),VerifyProjectResponse)
        End Function
        
        '<remarks/>
        Public Function BeginVerifyProject(ByVal projectId As String, ByVal sessionId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VerifyProject", New Object() {projectId, sessionId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndVerifyProject(ByVal asyncResult As System.IAsyncResult) As VerifyProjectResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),VerifyProjectResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddMerchantEx", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddMerchantEx( _
                    ByVal merchantUid As String,  _
                    ByVal merchantId As String,  _
                    ByVal merchantPassword As String,  _
                    ByVal firstName As String,  _
                    ByVal lastName As String,  _
                    ByVal email As String,  _
                    ByVal telephone As String,  _
                    ByVal street As String,  _
                    ByVal town As String,  _
                    ByVal city As String,  _
                    ByVal state As String,  _
                    ByVal country As String,  _
                    ByVal postalCode As String,  _
                    ByVal comments As String,  _
                    ByVal companyName As String,  _
                    ByVal childId As String,  _
                    ByVal childUid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("AddMerchantEx", New Object() {merchantUid, merchantId, merchantPassword, firstName, lastName, email, telephone, street, town, city, state, country, postalCode, comments, companyName, childId, childUid})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAddMerchantEx( _
                    ByVal merchantUid As String,  _
                    ByVal merchantId As String,  _
                    ByVal merchantPassword As String,  _
                    ByVal firstName As String,  _
                    ByVal lastName As String,  _
                    ByVal email As String,  _
                    ByVal telephone As String,  _
                    ByVal street As String,  _
                    ByVal town As String,  _
                    ByVal city As String,  _
                    ByVal state As String,  _
                    ByVal country As String,  _
                    ByVal postalCode As String,  _
                    ByVal comments As String,  _
                    ByVal companyName As String,  _
                    ByVal childId As String,  _
                    ByVal childUid As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddMerchantEx", New Object() {merchantUid, merchantId, merchantPassword, firstName, lastName, email, telephone, street, town, city, state, country, postalCode, comments, companyName, childId, childUid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddMerchantEx(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddMerchant", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function UpdatePassword(ByVal UpdatePasswordData As UpdatePasswordData) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("UpdatePassword", New Object() {UpdatePasswordData})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginUpdatePassword(ByVal UpdatePasswordData As UpdatePasswordData, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdatePassword", New Object() {UpdatePasswordData}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdatePassword(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddCustomer", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddOrder(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String, ByVal type As String, ByVal orderId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddOrder", New Object() {merchantData, customerData, childId, type, orderId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddOrder(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String, ByVal type As String, ByVal orderId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddOrder", New Object() {merchantData, customerData, childId, type, orderId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddOrder(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:CRMservices#AddCustomer", RequestNamespace:="urn:CRMservices", ResponseNamespace:="urn:CRMservices")>  _
        Public Function AddInvoice(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String, ByVal type As String, ByVal orderId As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ErrorResponse
            Dim results() As Object = Me.Invoke("AddInvoice", New Object() {merchantData, customerData, childId, type, orderId})
            Return CType(results(0),ErrorResponse)
        End Function
        
        '<remarks/>
        Public Function BeginAddInvoice(ByVal merchantData As MerchantData, ByVal customerData As CustomerData, ByVal childId As String, ByVal type As String, ByVal orderId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddInvoice", New Object() {merchantData, customerData, childId, type, orderId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddInvoice(ByVal asyncResult As System.IAsyncResult) As ErrorResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ErrorResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("MerchantData", "urn:CRMservices")>  _
    Public Class MerchantData
        
        '<remarks/>
        Public merchantUid As String
        
        '<remarks/>
        Public merchantId As String
        
        '<remarks/>
        Public merchantPassword As String
        
        '<remarks/>
        Public firstName As String
        
        '<remarks/>
        Public lastName As String
        
        '<remarks/>
        Public telephone As String
        
        '<remarks/>
        Public email As String
        
        '<remarks/>
        Public street As String
        
        '<remarks/>
        Public town As String
        
        '<remarks/>
        Public city As String
        
        '<remarks/>
        Public state As String
        
        '<remarks/>
        Public country As String
        
        '<remarks/>
        Public postalCode As String
        
        '<remarks/>
        Public comments As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("UpdatePasswordData", "urn:CRMservices")>  _
    Public Class UpdatePasswordData
        
        '<remarks/>
        Public merchantUid As String
        
        '<remarks/>
        Public merchantId As String
        
        '<remarks/>
        Public merchantPass As String
        
        '<remarks/>
        Public customerUid As String
        
        '<remarks/>
        Public customerPass As String
        
        '<remarks/>
        Public childId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("VerifyProjectResponse", "urn:CRMservices")>  _
    Public Class VerifyProjectResponse
        
        '<remarks/>
        Public verified As String
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public isOwner As String
        
        '<remarks/>
        Public projectName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("sinfo", "urn:CRMservices")>  _
    Public Class sinfo
        
        '<remarks/>
        Public serviceType As Integer
        
        '<remarks/>
        Public serviceName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ServiceData", "urn:CRMservices")>  _
    Public Class ServiceData
        
        '<remarks/>
        Public services() As sinfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("LoginResponse", "urn:CRMservices")>  _
    Public Class LoginResponse
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public errorDesc As String
        
        '<remarks/>
        Public sessionId As String
        
        '<remarks/>
        Public url As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ExtraServices", "urn:CRMservices")>  _
    Public Class ExtraServices
        
        '<remarks/>
        Public serviceName As String
        
        '<remarks/>
        Public serviceType As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ServicesInfo", "urn:CRMservices")>  _
    Public Class ServicesInfo
        
        '<remarks/>
        Public merchantId As String
        
        '<remarks/>
        Public merchantUid As String
        
        '<remarks/>
        Public merchantPassword As String
        
        '<remarks/>
        Public childId As String
        
        '<remarks/>
        Public extraServices() As ExtraServices
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("CustomerData", "urn:CRMservices")>  _
    Public Class CustomerData
        
        '<remarks/>
        Public customerUid As String
        
        '<remarks/>
        Public customerId As String
        
        '<remarks/>
        Public customerPassword As String
        
        '<remarks/>
        Public firstName As String
        
        '<remarks/>
        Public lastName As String
        
        '<remarks/>
        Public telephone As String
        
        '<remarks/>
        Public email As String
        
        '<remarks/>
        Public street As String
        
        '<remarks/>
        Public town As String
        
        '<remarks/>
        Public city As String
        
        '<remarks/>
        Public state As String
        
        '<remarks/>
        Public country As String
        
        '<remarks/>
        Public postalCode As String
        
        '<remarks/>
        Public comments As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ErrorResponse", "urn:CRMservices")>  _
    Public Class ErrorResponse
        
        '<remarks/>
        Public errorCode As String
        
        '<remarks/>
        Public errorDesc As String
    End Class
End Namespace
