'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CustomerSoap", [Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class Customer
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/account/customer.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerProcessing/CustomerProcessing/getActivationInfo", RequestNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", ResponseNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getActivationInfo(ByVal productinfo As activationinfo) As getActivationInfoResult
            Dim results() As Object = Me.Invoke("getActivationInfo", New Object() {productinfo})
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        Public Function BegingetActivationInfo(ByVal productinfo As activationinfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getActivationInfo", New Object() {productinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetActivationInfo(ByVal asyncResult As System.IAsyncResult) As getActivationInfoResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),getActivationInfoResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerProcessing/CustomerProcessing/activate", RequestNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", ResponseNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function activate(ByVal CustomerID As Integer, ByVal ProductCode As String, ByVal OrderNo As Integer, ByVal SerialNo As Integer, ByVal Language As String, ByVal CompanyName As String) As activateResult
            Dim results() As Object = Me.Invoke("activate", New Object() {CustomerID, ProductCode, OrderNo, SerialNo, Language, CompanyName})
            Return CType(results(0),activateResult)
        End Function
        
        '<remarks/>
        Public Function Beginactivate(ByVal CustomerID As Integer, ByVal ProductCode As String, ByVal OrderNo As Integer, ByVal SerialNo As Integer, ByVal Language As String, ByVal CompanyName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("activate", New Object() {CustomerID, ProductCode, OrderNo, SerialNo, Language, CompanyName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endactivate(ByVal asyncResult As System.IAsyncResult) As activateResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),activateResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerProcessing/CustomerProcessing/autoLogin", RequestNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", ResponseNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function autoLogin(ByVal logininfo As AutoLoginStruct) As AutoLoginResult
            Dim results() As Object = Me.Invoke("autoLogin", New Object() {logininfo})
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        Public Function BeginautoLogin(ByVal logininfo As AutoLoginStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("autoLogin", New Object() {logininfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndautoLogin(ByVal asyncResult As System.IAsyncResult) As AutoLoginResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AutoLoginResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerProcessing/CustomerProcessing/logOff", RequestNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", ResponseNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function logOff(ByVal logoffinfo As AutoLogOffStruct) As logoffReturnMsg
            Dim results() As Object = Me.Invoke("logOff", New Object() {logoffinfo})
            Return CType(results(0),logoffReturnMsg)
        End Function
        
        '<remarks/>
        Public Function BeginlogOff(ByVal logoffinfo As AutoLogOffStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("logOff", New Object() {logoffinfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndlogOff(ByVal asyncResult As System.IAsyncResult) As logoffReturnMsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),logoffReturnMsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomerProcessing/CustomerProcessing/authenticate", RequestNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", ResponseNamespace:="http://tempuri.org/CustomerProcessing/CustomerProcessing", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function authenticate(ByVal loginInfo As authenticateStruct) As authenticateResult
            Dim results() As Object = Me.Invoke("authenticate", New Object() {loginInfo})
            Return CType(results(0),authenticateResult)
        End Function
        
        '<remarks/>
        Public Function Beginauthenticate(ByVal loginInfo As authenticateStruct, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("authenticate", New Object() {loginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function Endauthenticate(ByVal asyncResult As System.IAsyncResult) As authenticateResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),authenticateResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class activationinfo
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public productcode As String
        
        '<remarks/>
        Public orderno As String
        
        '<remarks/>
        Public serialno As String
        
        '<remarks/>
        Public language As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class authenticateResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public customerid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class authenticateStruct
        
        '<remarks/>
        Public loginid As String
        
        '<remarks/>
        Public passward As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class logoffReturnMsg
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class AutoLogOffStruct
        
        '<remarks/>
        Public sid As String
        
        '<remarks/>
        Public refId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class AutoLoginResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public newwin As String
        
        '<remarks/>
        Public winparam As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
        
        '<remarks/>
        Public link As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class AutoLoginStruct
        
        '<remarks/>
        Public customerid As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public serviceid As String
        
        '<remarks/>
        Public language As String
        
        '<remarks/>
        Public loginid As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class activateResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/CustomerProcessing/CustomerProcessing")>  _
    Public Class getActivationInfoResult
        
        '<remarks/>
        Public ERRORCODE As String
        
        '<remarks/>
        Public ERRORDESC As String
        
        '<remarks/>
        Public link As String
        
        '<remarks/>
        Public variablename As String
        
        '<remarks/>
        Public value As String
    End Class
End Namespace
