'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace com.infinibiz.webservices1
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IBZservicesBinding", [Namespace]:="urn:IBZservices")>  _
    Public Class IBZservices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.infinibiz.com/updates.php"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#addReseller", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getSessionInfo(ByVal info As getparameter) As <System.Xml.Serialization.SoapElementAttribute("return")> returnmsg
            Dim results() As Object = Me.Invoke("getSessionInfo", New Object() {info})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BegingetSessionInfo(ByVal info As getparameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getSessionInfo", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetSessionInfo(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:IBZservices#getResellerToolbar", RequestNamespace:="urn:IBZservices", ResponseNamespace:="urn:IBZservices")>  _
        Public Function getResellerToolbar(ByVal info As getparameter) As <System.Xml.Serialization.SoapElementAttribute("return")> returnmsg
            Dim results() As Object = Me.Invoke("getResellerToolbar", New Object() {info})
            Return CType(results(0),returnmsg)
        End Function
        
        '<remarks/>
        Public Function BegingetResellerToolbar(ByVal info As getparameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResellerToolbar", New Object() {info}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndgetResellerToolbar(ByVal asyncResult As System.IAsyncResult) As returnmsg
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),returnmsg)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("getparameter", "urn:IBZservices")>  _
    Public Class getparameter
        
        '<remarks/>
        Public ITEM As String
        
        '<remarks/>
        Public CUSTOMER_UID As String
        
        '<remarks/>
        Public SESSIONID As String
        
        '<remarks/>
        Public LANGUAGE As String
        
        '<remarks/>
        Public REFERRER As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("returnmsg", "urn:IBZservices")>  _
    Public Class returnmsg
        
        '<remarks/>
        Public ITEM As String
        
        '<remarks/>
        Public VALUE As String
        
        '<remarks/>
        Public ERRORCODE As System.SByte
        
        '<remarks/>
        Public ERRORDESC As String
    End Class
End Namespace
